import argparse

def get_args():
    parse = argparse.ArgumentParser()
    parse.add_argument('--gamma', type=float, default=0.993, help='the discount factor of RL')
    parse.add_argument('--seed', type=int, default=123, help='the random seeds')
    parse.add_argument('--num-workers', type=int, default=8, help='the number of workers to collect samples')
    parse.add_argument('--env-name', type=str, default='academy_empty_goal_close', help='the environment name')
    parse.add_argument('--batch-size', type=int, default=8, help='the batch size of updating')
    parse.add_argument('--lr', type=float, default=0.00008, help='learning rate of the algorithm')
    parse.add_argument('--epoch', type=int, default=4, help='the epoch during training')
    parse.add_argument('--nsteps', type=int, default=128, help='the steps to collect samples')
    parse.add_argument('--vloss-coef', type=float, default=0.5, help='the coefficient of value loss')
    parse.add_argument('--ent-coef', type=float, default=0.01, help='the entropy loss coefficient')
    parse.add_argument('--tau', type=float, default=0.95, help='gae coefficient')
    parse.add_argument('--cuda', action='store_true', help='use cuda do the training')
    parse.add_argument('--total-frames', type=int, default=int(1e5), help='the total frames for training')
    parse.add_argument('--eps', type=float, default=1e-5, help='param for adam optimizer')
    parse.add_argument('--clip', type=float, default=0.27, help='the ratio clip param')
    parse.add_argument('--save-dir', type=str, default='saved_models/', help='the folder to save models')
    parse.add_argument('--lr-decay', action='store_true', help='if using the learning rate decay during decay')
    parse.add_argument('--max-grad-norm', type=float, default=0.5, help='grad norm')
    parse.add_argument('--display-interval', type=int, default=10, help='the interval that display log information')
    parse.add_argument('--log-dir', type=str, default='logs/')
    parse.add_argument('--policy_model_dir', type=str, default='policy_model')
    parse.add_argument('--numIters', type=int, default=1000)
    parse.add_argument('--numEps', type=int, default=2)
    parse.add_argument('--tempThreshold', type=int, default=15)
    parse.add_argument('--updateThreshold', type=float, default=0.6)
    parse.add_argument('--maxlenOfQueue', type=int, default=200000)
    parse.add_argument('--numMCTSSims', type=int, default=25)
    parse.add_argument('--gfootballCompare', type=int, default=40)
    parse.add_argument('--cpuct', type=int, default=1)
    parse.add_argument('--checkpoint', type=str, default='./temp/')
    parse.add_argument('--load_model', type=bool, default=False)
    parse.add_argument('--numItersForTrainExamplesHistory', type=str, default=20)

    args = parse.parse_args()

    return args
